services:
  - type: web
    name: astra-frontend
    env: static
    region: oregon
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    branch: main
    repo: <REPLACE_WITH_YOUR_REPO>
    plan: free
    autoDeploy: true
  - type: web
    name: astra-api
    env: docker
    region: oregon
    dockerfilePath: server/Dockerfile
    branch: main
    repo: <REPLACE_WITH_YOUR_REPO>
    plan: free
    autoDeploy: true
